# Force Xcode environment
language: objective-c

# Forces macOS 10.11
osx_image: xcode7.3

before_script:
  - gem uninstall -Vax --force --no-abort-on-dependent run_loop
  - scripts/ci/travis/instruments-auth.sh

script:
  - scripts/ci/travis/install-gem-ci.rb
  - scripts/ci/travis/rspec-ci.rb
  - bundle exec rspec spec/integration/detect_simulators_spec.rb
  - bundle exec rspec spec/integration/simctl_spec.rb

rvm:
  - 2.0.0
  - 2.1.7
  - 2.2.3

notifications:
  email:
    recipients:
      - joshuajmoody@gmail.com
      - chris.fuentes@xamarin.com
    on_success: change
    on_failure: always
  slack:
    rooms:
      secure: j15+d9xbUbGIyX4mmTmWP4EUg13LFiyeSGoVvpjsrPyoCR78V4jqbunLON55KczLQD5ql+xBwv34x57UZhca8g74ZBulF7A5xm7oxSyOgMOB1hgf5ruEU3n8dtWvHFvuLUyreu2QYrmGPznJnEOXE0feFuDBiyp1BpTvk4gwr+4=

