language: objective-c
cache: bundle

before_script:
  - gem uninstall -Vax --force --no-abort-on-dependent run_loop
  - scripts/ci/travis/instruments-auth.sh

script:
  - scripts/ci/travis/install-gem-ci.rb
  - scripts/ci/travis/rspec-ci.rb

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.2

notifications:
  notifications:
      email: false
  slack:
    secure: gWmLS+smElUJwiCF0PYPPkFVDEowNhaD6yD9T3QxRAOamUahVq20NQg8qy1Gj2niiFDlbqYKpZZlZEwLyrcEbwWsBgyYYdNRphEqxBySzbWXZ9ebxwT7tp4bv8NMoVBe0WODx0L3kt48IUcUoSHU/aOBYmPRzf0rTFCZcwqd0W4=#calabash
